//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Forms.Resource {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Forms.Resource.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido materno debe contener máximo 50 caracteres..
        /// </summary>
        internal static string ApellidoMaternoLongitud {
            get {
                return ResourceManager.GetString("ApellidoMaternoLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido materno es requerido..
        /// </summary>
        internal static string ApellidoMaternoRequerido {
            get {
                return ResourceManager.GetString("ApellidoMaternoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido paterno debe contener máximo 50 caracteres..
        /// </summary>
        internal static string ApellidoPaternoLongitud {
            get {
                return ResourceManager.GetString("ApellidoPaternoLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido paterno requerido..
        /// </summary>
        internal static string ApellidoPaternoRequerido {
            get {
                return ResourceManager.GetString("ApellidoPaternoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto longitud requerido..
        /// </summary>
        internal static string AsuntoLongitud {
            get {
                return ResourceManager.GetString("AsuntoLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto requerido..
        /// </summary>
        internal static string AsuntoRequerido {
            get {
                return ResourceManager.GetString("AsuntoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico no cumple con la estructura adecuada..
        /// </summary>
        internal static string EmailEstructura {
            get {
                return ResourceManager.GetString("EmailEstructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico debe contener máximo 150 caracteres..
        /// </summary>
        internal static string EmailLongitud {
            get {
                return ResourceManager.GetString("EmailLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico es requerido..
        /// </summary>
        internal static string EmailRequerido {
            get {
                return ResourceManager.GetString("EmailRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error requerido..
        /// </summary>
        internal static string ErrorRequerido {
            get {
                return ResourceManager.GetString("ErrorRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha requerida..
        /// </summary>
        internal static string FechaRequerida {
            get {
                return ResourceManager.GetString("FechaRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El genéro es requerido..
        /// </summary>
        internal static string GeneroRequerido {
            get {
                return ResourceManager.GetString("GeneroRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El mensaje debe contener máximo 250 caracteres..
        /// </summary>
        internal static string MensajeLongitud {
            get {
                return ResourceManager.GetString("MensajeLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje requerido..
        /// </summary>
        internal static string MensajeRequerido {
            get {
                return ResourceManager.GetString("MensajeRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Método requerido..
        /// </summary>
        internal static string MetodoRequerido {
            get {
                return ResourceManager.GetString("MetodoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre debe contener máximo 50 caracteres..
        /// </summary>
        internal static string NombreLongitud {
            get {
                return ResourceManager.GetString("NombreLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es requerido..
        /// </summary>
        internal static string NombreRequerido {
            get {
                return ResourceManager.GetString("NombreRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña actual es requerida..
        /// </summary>
        internal static string PasswordActualLongitud {
            get {
                return ResourceManager.GetString("PasswordActualLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña actual debe contener entre 8 y 32 caracteres..
        /// </summary>
        internal static string PasswordActualRequerido {
            get {
                return ResourceManager.GetString("PasswordActualRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contener entre 8 y 32 caracteres..
        /// </summary>
        internal static string PasswordLongitud {
            get {
                return ResourceManager.GetString("PasswordLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña es requerida..
        /// </summary>
        internal static string PasswordRequerido {
            get {
                return ResourceManager.GetString("PasswordRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El perfil es requerido..
        /// </summary>
        internal static string PerfilRequerido {
            get {
                return ResourceManager.GetString("PerfilRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un permiso..
        /// </summary>
        internal static string PermisosRequerido {
            get {
                return ResourceManager.GetString("PermisosRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PermisosRequeridos.
        /// </summary>
        internal static string PermisosRequeridos {
            get {
                return ResourceManager.GetString("PermisosRequeridos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plataforma requerida..
        /// </summary>
        internal static string PlataformaRequerida {
            get {
                return ResourceManager.GetString("PlataformaRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El teléfono debe contener 10 digitos..
        /// </summary>
        internal static string TelefonoLongitud {
            get {
                return ResourceManager.GetString("TelefonoLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El télefono es requerido..
        /// </summary>
        internal static string TelefonoRequerido {
            get {
                return ResourceManager.GetString("TelefonoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario debe contener máximo 20 caracteres..
        /// </summary>
        internal static string UsernameLongitud {
            get {
                return ResourceManager.GetString("UsernameLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario es requerido..
        /// </summary>
        internal static string UsernameRequerido {
            get {
                return ResourceManager.GetString("UsernameRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id usuario requerido..
        /// </summary>
        internal static string UsuarioIdRequerido {
            get {
                return ResourceManager.GetString("UsuarioIdRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ValorLongitud.
        /// </summary>
        internal static string ValorLongitud {
            get {
                return ResourceManager.GetString("ValorLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del parámetro es requerido..
        /// </summary>
        internal static string ValorRequerido {
            get {
                return ResourceManager.GetString("ValorRequerido", resourceCulture);
            }
        }
    }
}
